/**
 * Ada Spot — starter ("read this first") disclaimers, shown at the TOP of the
 * free screening and the paid report.
 *
 * DRAFT copy — legal-adjacent. Gina / Kelley (JD) should finalize the exact
 * wording before any public launch. Kept here so it's a single edit point.
 * The end-of-report disclaimer (SPOT_REPORT_DISCLAIMER) still applies too.
 */

export const SPOT_FREE_STARTER_DISCLAIMER =
  'Quick heads-up: this is an automated screening — an AI reading your photo. ' +
  'It can miss things or get them wrong, so treat it as a starting point, not a ' +
  'professional inspection or legal advice. Anything important, confirm on-site.';

export const SPOT_REPORT_STARTER_DISCLAIMER =
  'Please read this first. This report is an automated accessibility screening ' +
  'generated by AI from the photos you provided. AI can make mistakes — it may ' +
  'misread a photo, miss a barrier, or flag something that isn\u2019t one — so treat ' +
  'everything here as a starting point for planning, not a final answer. This is ' +
  'not a professional on-site inspection and it is not legal advice; ADA Legal Link ' +
  'is not acting as your attorney, and nothing here certifies that your property is ' +
  'or isn\u2019t ADA-compliant. Before relying on any finding, confirm measurements and ' +
  'conditions on-site and, for your situation, consult a qualified accessibility ' +
  'professional and/or an attorney.';
