import React, { useState, useRef, useEffect, useCallback } from 'react';
const URL = 'https://www.ada.gov/law-and-regs/design-standards/2010-stds/#806-transient-lodging-guest-rooms';
const C = [
  { id: 1, label: 'Accessible Route', section: '§806.2.2', color: '#C2410C', x: 100, y: 42, plain: 'A 36-inch clear accessible route must connect the room entry door to all functional areas: bed(s), bathroom, desk/work surface, closet, and balcony if provided. The route cannot require navigating around furniture that blocks passage. All floor surfaces must be firm, stable, and slip-resistant with no abrupt level changes.', legal: '"An accessible route complying with §402 shall connect all accessible spaces and elements within the guest room."', citation: '§806.2.2' },
  { id: 2, label: 'Bed Clearance', section: '§806.2.3', color: '#16A34A', x: 300, y: 42, plain: 'In rooms with two beds, 36 inches of clear floor space must be provided on both sides of each bed (between beds and on outside edges). In single-bed rooms, 36 inches is required on one side only. Clearance is measured from the edge of the bed frame or mattress, whichever extends further. This space allows wheelchair transfer.', legal: '"Clear floor space 36 inches wide minimum shall be provided along both sides of a bed." Single bed: one side only. Measured from bed frame/mattress edge.', citation: '§806.2.3' },
  { id: 3, label: 'Bathroom', section: '§806.2.4', color: '#2563EB', x: 500, y: 42, plain: 'The bathroom must include an accessible toilet (§604), either an accessible bathtub (§607) or roll-in shower (§608), and an accessible lavatory (§606). The bathroom door must provide 32 inches clear width and cannot swing into the clear floor space of any fixture. Grab bars, mirror height (40 inches max), and towel/amenity reach ranges all apply.', legal: '"Bathrooms shall comply with §603." Toilet per §604, tub/shower per §607/§608, lavatory per §606. Door shall not swing into fixture clearances.', citation: '§806.2.4' },
  { id: 4, label: 'Controls', section: '§806.2.5', color: '#7C3AED', x: 100, y: 260, plain: 'All operable controls within the room must be within reach range (15-48 inches above floor) and operable with one hand. This includes: light switches, HVAC thermostat, drapery/curtain controls, electrical outlets, lamp switches, and bedside phone. All per §309 (max 5 lbs force, no twisting).', legal: '"Operable parts shall comply with §309." Controls within reach range per §308. Includes all room controls: HVAC, lighting, drapes, outlets.', citation: '§806.2.5' },
  { id: 5, label: 'Communication', section: '§806.3', color: '#D97706', x: 300, y: 260, plain: 'Rooms designated for hearing-impaired guests must have: visible notification devices (flashing light) for door knock, telephone ring, and fire alarm. An electrical outlet at the desk and nightstand for a portable TTY. A visual notification device connected to the hotel\'s alarm system. A telephone with volume control.', legal: '§806.3 "Guest rooms required to provide communication features shall comply." Visual notification for: "incoming telephone calls, door knock/bell, and building fire alarm."', citation: '§806.3' },
  { id: 6, label: 'Doors', section: '§806.2.1', color: '#DB2777', x: 500, y: 260, plain: 'The entry door must provide 32 inches clear width minimum with maneuvering clearance per §404. All interior doors (bathroom, closet) must also be accessible. Hardware must be lever-type (no round knobs). The door peephole must be at 43 inches max for a seated person. A secondary peephole at standing height is recommended.', legal: '"Doors shall comply with §404." Clear width: 32 inches min. Hardware per §309. Peephole within reach range.', citation: '§806.2.1' },
  { id: 7, label: 'Scoping', section: '§224', color: '#0EA5E9', x: 700, y: 150, plain: 'The number of accessible rooms depends on total: 1-25 rooms = 1 mobility; 26-50 = 2; 51-75 = 3; 76-100 = 4; and so on. Communication-accessible rooms follow a similar table. Accessible rooms must be dispersed among room types (king, double, suite) and price categories. Cannot be all concentrated in one type.', legal: '§224.2 "Guest rooms with mobility features: 1-25 = 1; 26-50 = 2; 51-75 = 3." Communication features at similar ratios. Dispersed per §224.5.', citation: '§224' }
];
function makeLink(t){return(<a href={URL} target="_blank" rel="noopener noreferrer" style={{color:'#C2410C',textDecoration:'none',borderBottom:'1px dotted #C2410C'}}>{t}<span aria-hidden="true" style={{fontSize:'.65em',marginLeft:1,verticalAlign:'super'}}>↗</span></a>)}
function pc(t){return t.split(/(§\d{3,4}(?:\.\d+)*)/g).map((p,i)=>/^§\d{3,4}/.test(p)?<React.Fragment key={i}>{makeLink(p)}</React.Fragment>:p)}
export default function GuestRoomDiagram(){const[a,sa]=useState(null);const[m,sm]=useState(false);const pr=useRef(null);const tg=useCallback(id=>sa(p=>p===id?null:id),[]);useEffect(()=>{if(a&&pr.current)pr.current.scrollIntoView({behavior:'smooth',block:'nearest'})},[a]);useEffect(()=>{const h=e=>{if(e.key==='Escape')sa(null)};window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h)},[]);const d=(i,mm)=>m?`${mm} mm`:`${i}"`;const ac=C.find(c=>c.id===a);
return(<div style={{margin:'32px 0'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:8,flexWrap:'wrap',gap:8}}><h3 style={{fontFamily:'Fraunces, serif',fontSize:'1.15rem',fontWeight:700,color:'var(--slate-900)',margin:0}}>§806 Guest Rooms</h3><div style={{display:'flex',gap:6,alignItems:'center'}}><span style={{fontFamily:'Manrope, sans-serif',fontSize:'0.8rem',color:'var(--slate-500)'}}>Units:</span>{['Imperial','Metric'].map(u=>{const isA=u==='Metric'?m:!m;return(<button key={u} onClick={()=>sm(u==='Metric')} aria-pressed={isA} style={{fontFamily:'Manrope, sans-serif',fontSize:'0.75rem',fontWeight:isA?700:500,padding:'4px 10px',borderRadius:6,border:'1px solid var(--slate-200)',background:isA?'#1A1F2B':'white',color:isA?'white':'var(--slate-600)',cursor:'pointer',minHeight:28}}>{u}</button>)})}</div></div>
<div style={{background:'white',border:'1px solid var(--slate-200)',borderRadius:12,overflow:'hidden'}}><svg viewBox="0 0 900 420" role="img" aria-labelledby="gr-t" style={{width:'100%',height:'auto',display:'block'}}><title id="gr-t">ADA §806 Guest Room — Plan View</title><rect width="900" height="420" fill="#FAFAF9"/>
<text x="450" y="24" textAnchor="middle" fontFamily="Manrope, sans-serif" fontSize="10" fontWeight="700" fill="#94A3B8" letterSpacing=".08em">PLAN VIEW — ACCESSIBLE GUEST ROOM</text>
{/* Room walls */}<rect x="60" y="50" width="780" height="340" rx="4" fill="white" stroke="#94A3B8" strokeWidth="2"/>
{/* Entry door */}<rect x="56" y="180" width="8" height="60" fill="#FAFAF9"/><line x1="64" y1="180" x2="64" y2="240" stroke="#DB2777" strokeWidth="3"/><text x="45" y="215" fontFamily="Manrope, sans-serif" fontSize="7" fill="#DB2777" fontWeight="600" transform="rotate(-90 45 215)">ENTRY</text>
{/* Bed 1 */}<rect x="200" y="80" width="180" height="110" rx="6" fill="#E7E5E4" opacity="0.2" stroke="#94A3B8" strokeWidth="1.5"/><text x="290" y="140" textAnchor="middle" fontFamily="Manrope, sans-serif" fontSize="9" fill="#94A3B8">BED 1</text>
{/* Bed 2 */}<rect x="200" y="230" width="180" height="110" rx="6" fill="#E7E5E4" opacity="0.2" stroke="#94A3B8" strokeWidth="1.5"/><text x="290" y="290" textAnchor="middle" fontFamily="Manrope, sans-serif" fontSize="9" fill="#94A3B8">BED 2</text>
{/* 36" clearances */}<rect x="200" y="190" width="180" height="40" rx="2" fill="#16A34A" opacity="0.06" stroke="#16A34A" strokeWidth="1" strokeDasharray="4 3"/><text x="290" y="214" textAnchor="middle" fontFamily="Manrope, sans-serif" fontSize="7" fill="#16A34A" fontWeight="600">{d('36','915')} between beds</text>
<rect x="130" y="80" width="70" height="260" rx="2" fill="#16A34A" opacity="0.04" stroke="#16A34A" strokeWidth="1" strokeDasharray="4 3"/><text x="165" y="215" textAnchor="middle" fontFamily="Manrope, sans-serif" fontSize="6" fill="#16A34A">{d('36','915')}</text>
{/* Accessible route */}<path d="M 64 210 L 130 210 L 130 130 L 200 130" fill="none" stroke="#C2410C" strokeWidth="2" strokeDasharray="6 3"/><path d="M 130 210 L 130 290 L 200 290" fill="none" stroke="#C2410C" strokeWidth="2" strokeDasharray="6 3"/><path d="M 130 210 L 500 210 L 500 130" fill="none" stroke="#C2410C" strokeWidth="2" strokeDasharray="6 3"/>
<text x="350" y="204" fontFamily="Manrope, sans-serif" fontSize="7" fill="#C2410C" fontWeight="600">{d('36','915')} ROUTE</text>
{/* Nightstands */}<rect x="380" y="95" width="40" height="35" rx="3" fill="#E7E5E4" opacity="0.15" stroke="#94A3B8" strokeWidth="1"/><rect x="380" y="290" width="40" height="35" rx="3" fill="#E7E5E4" opacity="0.15" stroke="#94A3B8" strokeWidth="1"/>
{/* Desk */}<rect x="450" y="65" width="120" height="50" rx="3" fill="#E7E5E4" opacity="0.15" stroke="#94A3B8" strokeWidth="1"/><text x="510" y="94" textAnchor="middle" fontFamily="Manrope, sans-serif" fontSize="7" fill="#94A3B8">DESK</text>
{/* Bathroom */}<rect x="600" y="50" width="230" height="180" rx="4" fill="#2563EB" opacity="0.04" stroke="#2563EB" strokeWidth="1.5"/><text x="715" y="145" textAnchor="middle" fontFamily="Manrope, sans-serif" fontSize="9" fill="#2563EB" fontWeight="600">BATHROOM</text><text x="715" y="160" textAnchor="middle" fontFamily="Manrope, sans-serif" fontSize="7" fill="#2563EB">Toilet · Shower · Lavatory</text>
{/* Closet */}<rect x="600" y="280" width="100" height="100" rx="3" fill="#E7E5E4" opacity="0.1" stroke="#94A3B8" strokeWidth="1"/><text x="650" y="335" textAnchor="middle" fontFamily="Manrope, sans-serif" fontSize="7" fill="#94A3B8">CLOSET</text>
{/* Controls */}<rect x="440" y="345" width="120" height="30" rx="4" fill="#7C3AED" opacity="0.04" stroke="#7C3AED" strokeWidth="1"/><text x="500" y="364" textAnchor="middle" fontFamily="Manrope, sans-serif" fontSize="6.5" fill="#7C3AED">HVAC · Lights · Drapes</text>
{/* Communication */}<rect x="720" y="290" width="100" height="45" rx="4" fill="#D97706" opacity="0.04" stroke="#D97706" strokeWidth="1"/><text x="770" y="310" textAnchor="middle" fontFamily="Manrope, sans-serif" fontSize="6.5" fill="#D97706" fontWeight="500">Visual alerts:</text><text x="770" y="324" textAnchor="middle" fontFamily="Manrope, sans-serif" fontSize="6" fill="#D97706">🔔 Door · ☎ Phone · 🚨 Alarm</text>
{C.map(c=>(<g key={c.id} tabIndex="0" role="button" aria-label={`Callout ${c.id}: ${c.label}`} aria-expanded={a===c.id} onClick={()=>tg(c.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();tg(c.id)}}} style={{cursor:'pointer',outline:'none'}}>{a===c.id&&<circle cx={c.x} cy={c.y} r="18" fill="none" stroke={c.color} strokeWidth="2" opacity=".3"><animate attributeName="r" from="14" to="22" dur="1.2s" repeatCount="indefinite"/><animate attributeName="opacity" from=".4" to="0" dur="1.2s" repeatCount="indefinite"/></circle>}<circle cx={c.x} cy={c.y} r="13" fill={a===c.id?c.color:'white'} stroke={c.color} strokeWidth="2"/><text x={c.x} y={c.y+4} textAnchor="middle" fontFamily="Manrope, sans-serif" fontSize="11" fontWeight="700" fill={a===c.id?'white':c.color}>{c.id}</text></g>))}
<text x="30" y="410" fontFamily="Manrope, sans-serif" fontSize="9" fill="#94A3B8">Click or tap numbered callouts for details</text></svg></div>
<div aria-live="polite" className="sr-only">{ac?`Showing callout ${ac.id}: ${ac.label}`:''}</div>
{ac&&(<div ref={pr} style={{marginTop:12,background:'white',border:'1px solid var(--slate-200)',borderRadius:12,overflow:'hidden',animation:'grF .25s ease-out'}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'14px 20px',borderBottom:'1px solid var(--slate-200)',background:'#FAFAF9',flexWrap:'wrap',gap:8}}><div style={{display:'flex',alignItems:'center',gap:10,flexWrap:'wrap'}}><span style={{display:'inline-flex',alignItems:'center',justifyContent:'center',width:26,height:26,borderRadius:'50%',background:ac.color,color:'white',fontFamily:'Manrope, sans-serif',fontSize:'0.8rem',fontWeight:700}}>{ac.id}</span><span style={{fontFamily:'Fraunces, serif',fontSize:'1.1rem',fontWeight:700,color:'var(--slate-900)'}}>{ac.label}</span><span style={{fontFamily:'Manrope, sans-serif',fontSize:'0.75rem',fontWeight:600,color:ac.color,background:`${ac.color}15`,padding:'2px 8px',borderRadius:4}}>{ac.section}</span></div><button onClick={()=>sa(null)} aria-label="Close" style={{background:'none',border:'1px solid var(--slate-200)',borderRadius:6,padding:'4px 10px',cursor:'pointer',fontFamily:'Manrope, sans-serif',fontSize:'0.75rem',color:'var(--slate-500)',minHeight:30}}>Close ✕</button></div><div className="guide-two-col" style={{padding:20,gap:24,margin:0}}><div style={{flex:'1 1 55%',minWidth:0}}><p style={{fontFamily:'Manrope, sans-serif',fontSize:'0.9375rem',color:'var(--slate-700)',lineHeight:1.75,margin:0}}>{ac.plain}</p></div><aside style={{flex:'1 1 40%',minWidth:0}}><div style={{background:'#FFFBF7',borderLeft:'3px solid #C2410C',borderRadius:'0 10px 10px 0',padding:'16px 18px'}}><p style={{fontFamily:'Manrope, sans-serif',fontSize:'0.7rem',fontWeight:700,letterSpacing:'0.1em',textTransform:'uppercase',color:'var(--slate-500)',margin:'0 0 8px'}}>Official Standard — {pc(ac.citation)}</p><p style={{fontFamily:'Manrope, sans-serif',fontSize:'0.875rem',color:'var(--slate-600)',lineHeight:1.7,margin:0,fontStyle:'italic'}}>{pc(ac.legal)}</p></div></aside></div></div>)}
<style>{`@keyframes grF{from{opacity:0;transform:translateY(-8px)}to{opacity:1;transform:translateY(0)}}`}</style></div>)}