import React, { useState, useRef, useEffect, useCallback } from 'react';
const URL='https://www.ada.gov/law-and-regs/design-standards/2010-stds/#804-kitchens-and-kitchenettes';
const C=[{id:1,label:'Work Surface',section:'§804.3',color:'#C2410C',x:100,y:42,plain:'At least one section of countertop must be 34 inches max above the floor, at least 30 inches wide, with knee and toe clearance underneath per §306. This lowered section serves as a work surface for food prep, placing items, or eating. The surface must be smooth and the knee space must be free of plumbing or structural elements.',legal:'"At least one work surface shall be 34 inches maximum above the finish floor." Width: 30 inches min. Knee clearance per §306.',citation:'§804.3'},
{id:2,label:'Clearance',section:'§804.2.1',color:'#16A34A',x:300,y:42,plain:'Pass-through (galley) kitchens: 40 inches clear between opposing counters or appliances. U-shaped kitchens: 60 inches clear in the center for wheelchair turning. Exception: if the cooktop or sink is not located at the base of the U, 40 inches is acceptable. The clearance must be maintained even when appliance doors are closed.',legal:'"Clearance between all opposing base cabinets, counter tops, appliances, or walls shall be 40 inches minimum." U-shaped: 60 inches for turning.',citation:'§804.2.1'},
{id:3,label:'Sink',section:'§804.4',color:'#2563EB',x:500,y:42,plain:'Kitchen sinks must be mounted at 34 inches max above the floor with knee and toe clearance underneath. The faucet must be operable with one hand (lever or sensor). Exposed pipes must be insulated. A shallow-bowl sink (6.5 inches deep max) is recommended to maximize knee clearance while maintaining function.',legal:'"Sinks shall comply with §606." Rim: 34 inches max. Knee clearance per §306. Faucet per §309.',citation:'§804.4'},
{id:4,label:'Appliances',section:'§804.5',color:'#7C3AED',x:100,y:260,plain:'Clear floor space (30 × 48 inches) must be provided at each appliance. Ovens: side-opening doors preferred; controls on front panel (not behind burners). Dishwashers: clear floor space adjacent for loading. Refrigerators: at least 50% of freezer space must be within reach range (15-48 inches). Microwave: front-mounted controls within reach.',legal:'"At least one of each type of appliance shall have clear floor space per §305." Oven controls on front. 50% of freezer within reach.',citation:'§804.5'},
{id:5,label:'Storage',section:'§804.5',color:'#D97706',x:300,y:260,plain:'At least 50% of shelf space in the kitchen must be within reach range (15-48 inches above floor). Upper cabinets are typically out of reach — solutions include pull-down shelf hardware, lazy susans, or placing essential items in lower cabinets. Pantry shelves must have 50% accessible storage as well.',legal:'"50 percent of shelf space in cabinets shall be within the reach ranges per §308." Pull-out or adjustable shelving recommended.',citation:'§804.5'},
{id:6,label:'Cooktop',section:'§804.6.4',color:'#DB2777',x:500,y:260,plain:'Clear floor space for forward or parallel approach at the cooktop. Controls must be on the front panel — never at the back where a user must reach over hot burners. Knee clearance underneath is preferred but not always required. A smooth-top (electric) cooktop is safer than open gas burners for wheelchair users.',legal:'"Controls for cooktops shall not require reaching across burners." Clear floor space per §305. Front- or side-mounted controls.',citation:'§804.6.4'},
{id:7,label:'Scoping',section:'§212',color:'#0EA5E9',x:700,y:150,plain:'Full kitchens in accessible dwelling units must comply. Hotel rooms with kitchenettes in mobility-accessible rooms must comply. Common-use kitchens in employee break rooms must have at least one accessible work surface and appliance set. Temporary kitchens (catering setups) are not covered.',legal:'§212.2 "Kitchens and kitchenettes in accessible dwelling units shall comply with §804." Common-use kitchens per §212.3.',citation:'§212'}];
function makeLink(t){return(<a href={URL} target="_blank" rel="noopener noreferrer" style={{color:'#C2410C',textDecoration:'none',borderBottom:'1px dotted #C2410C'}}>{t}<span aria-hidden="true" style={{fontSize:'.65em',marginLeft:1,verticalAlign:'super'}}>↗</span></a>)}
function pc(t){return t.split(/(§\d{3,4}(?:\.\d+)*)/g).map((p,i)=>/^§\d{3,4}/.test(p)?<React.Fragment key={i}>{makeLink(p)}</React.Fragment>:p)}
export default function KitchenDiagram(){const[a,sa]=useState(null);const[m,sm]=useState(false);const pr=useRef(null);const tg=useCallback(id=>sa(p=>p===id?null:id),[]);useEffect(()=>{if(a&&pr.current)pr.current.scrollIntoView({behavior:'smooth',block:'nearest'})},[a]);useEffect(()=>{const h=e=>{if(e.key==='Escape')sa(null)};window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h)},[]);const d=(i,mm)=>m?`${mm} mm`:`${i}"`;const ac=C.find(c=>c.id===a);
return(<div className="ada-diagram-wrap" style={{margin:'32px 0'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:8,flexWrap:'wrap',gap:8}}><h3 style={{fontFamily:'Fraunces, serif',fontSize:'1.15rem',fontWeight:700,color:'var(--slate-900)',margin:0}}>§804 Kitchens & Kitchenettes</h3><div style={{display:'flex',gap:6,alignItems:'center'}}><span style={{fontFamily:'Manrope, sans-serif',fontSize:'0.8rem',color:'var(--slate-500)'}}>Units:</span>{['Imperial','Metric'].map(u=>{const isA=u==='Metric'?m:!m;return(<button key={u} onClick={()=>sm(u==='Metric')} aria-pressed={isA} style={{fontFamily:'Manrope, sans-serif',fontSize:'0.75rem',fontWeight:isA?700:500,padding:'4px 10px',borderRadius:6,border:'1px solid var(--slate-200)',background:isA?'#1A1F2B':'white',color:isA?'white':'var(--slate-600)',cursor:'pointer',minHeight:28}}>{u}</button>)})}</div></div>
<div style={{background:'white',border:'1px solid var(--slate-200)',borderRadius:12,overflow:'hidden'}}><svg viewBox="0 0 900 420" role="img" aria-labelledby="kt-t" style={{width:'100%',height:'auto',display:'block'}}><title id="kt-t">ADA §804 Kitchens — U-Shaped and Galley Layouts</title><rect width="900" height="420" fill="#FAFAF9"/>
<text x="220" y="24" textAnchor="middle" fontFamily="Manrope, sans-serif" fontSize="10" fontWeight="700" fill="#4B5563" letterSpacing=".08em">U-SHAPED KITCHEN</text>
{/* U-shaped: top counter */}<rect x="60" y="50" width="320" height="40" rx="3" fill="#E7E5E4" opacity="0.2" stroke="#94A3B8" strokeWidth="1.5"/><text x="220" y="74" textAnchor="middle" fontFamily="Manrope, sans-serif" fontSize="7" fill="#4B5563">COUNTER + COOKTOP</text>
{/* Left counter */}<rect x="60" y="50" width="40" height="280" rx="3" fill="#E7E5E4" opacity="0.2" stroke="#94A3B8" strokeWidth="1.5"/><text x="80" y="200" textAnchor="middle" fontFamily="Manrope, sans-serif" fontSize="7" fill="#4B5563" transform="rotate(-90 80 200)">COUNTER + SINK</text>
{/* Right counter */}<rect x="340" y="50" width="40" height="280" rx="3" fill="#E7E5E4" opacity="0.2" stroke="#94A3B8" strokeWidth="1.5"/><text x="360" y="200" textAnchor="middle" fontFamily="Manrope, sans-serif" fontSize="7" fill="#4B5563" transform="rotate(90 360 200)">COUNTER + FRIDGE</text>
{/* 60" turning */}<circle cx="220" cy="210" r="70" fill="none" stroke="#16A34A" strokeWidth="1.5" strokeDasharray="5 3" opacity="0.4"/><text x="220" y="215" textAnchor="middle" fontFamily="Manrope, sans-serif" fontSize="8" fill="#16A34A" fontWeight="600">{d('60','1525')} turning</text>
{/* Work surface lowered */}<rect x="100" y="90" width="60" height="6" rx="2" fill="#C2410C" opacity="0.3" stroke="#C2410C" strokeWidth="1"/><text x="130" y="108" textAnchor="middle" fontFamily="Manrope, sans-serif" fontSize="6" fill="#C2410C" fontWeight="500">{d('34','865')} max</text>
{/* Divider */}<line x1="440" y1="20" x2="440" y2="410" stroke="#E2E8F0" strokeWidth="1" strokeDasharray="4 4"/>
<text x="670" y="24" textAnchor="middle" fontFamily="Manrope, sans-serif" fontSize="10" fontWeight="700" fill="#4B5563" letterSpacing=".08em">GALLEY KITCHEN</text>
{/* Galley left */}<rect x="490" y="50" width="340" height="40" rx="3" fill="#E7E5E4" opacity="0.2" stroke="#94A3B8" strokeWidth="1.5"/><text x="660" y="74" textAnchor="middle" fontFamily="Manrope, sans-serif" fontSize="7" fill="#4B5563">COUNTER + COOKTOP + SINK</text>
{/* Galley right */}<rect x="490" y="300" width="340" height="40" rx="3" fill="#E7E5E4" opacity="0.2" stroke="#94A3B8" strokeWidth="1.5"/><text x="660" y="324" textAnchor="middle" fontFamily="Manrope, sans-serif" fontSize="7" fill="#4B5563">COUNTER + FRIDGE</text>
{/* 40" clearance */}<line x1="470" y1="90" x2="470" y2="300" stroke="#16A34A" strokeWidth="1"/><line x1="464" y1="90" x2="476" y2="90" stroke="#16A34A" strokeWidth="1"/><line x1="464" y1="300" x2="476" y2="300" stroke="#16A34A" strokeWidth="1"/><rect x="448" y="188" width="42" height="13" rx="3" fill="#16A34A"/><text x="469" y="197" textAnchor="middle" fontFamily="Manrope, sans-serif" fontSize="7" fontWeight="700" fill="white">{d('40','1015')}</text>
{/* Wheelchair in galley */}<circle cx="660" cy="195" r="12" fill="#E2E8F0" stroke="#475569" strokeWidth="1"/><rect x="648" y="175" width="24" height="15" rx="3" fill="none" stroke="#64748B" strokeWidth="1"/><circle cx="650" cy="215" r="7" fill="none" stroke="#64748B" strokeWidth=".8"/><circle cx="670" cy="215" r="7" fill="none" stroke="#64748B" strokeWidth=".8"/>
{C.map(c=>(<g key={c.id} tabIndex="0" role="button" aria-label={`Callout ${c.id}: ${c.label}`} aria-expanded={a===c.id} onClick={()=>tg(c.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();tg(c.id)}}} style={{cursor:'pointer',outline:'none'}}>{a===c.id&&<circle cx={c.x} cy={c.y} r="18" fill="none" stroke={c.color} strokeWidth="2" opacity=".3"><animate attributeName="r" from="14" to="22" dur="1.2s" repeatCount="indefinite"/><animate attributeName="opacity" from=".4" to="0" dur="1.2s" repeatCount="indefinite"/></circle>}<circle cx={c.x} cy={c.y} r="13" fill={a===c.id?c.color:'white'} stroke={c.color} strokeWidth="2"/><text x={c.x} y={c.y+4} textAnchor="middle" fontFamily="Manrope, sans-serif" fontSize="11" fontWeight="700" fill={a===c.id?'white':c.color}>{c.id}</text></g>))}
<text x="30" y="410" fontFamily="Manrope, sans-serif" fontSize="9" fill="#4B5563">Click or tap numbered callouts for details</text></svg></div>
<div aria-live="polite" className="sr-only">{ac?`Showing callout ${ac.id}: ${ac.label}`:''}</div>
{ac&&(<div ref={pr} style={{marginTop:12,background:'white',border:'1px solid var(--slate-200)',borderRadius:12,overflow:'hidden',animation:'ktF .25s ease-out'}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'14px 20px',borderBottom:'1px solid var(--slate-200)',background:'#FAFAF9',flexWrap:'wrap',gap:8}}><div style={{display:'flex',alignItems:'center',gap:10,flexWrap:'wrap'}}><span style={{display:'inline-flex',alignItems:'center',justifyContent:'center',width:26,height:26,borderRadius:'50%',background:ac.color,color:'white',fontFamily:'Manrope, sans-serif',fontSize:'0.8rem',fontWeight:700}}>{ac.id}</span><span style={{fontFamily:'Fraunces, serif',fontSize:'1.1rem',fontWeight:700,color:'var(--slate-900)'}}>{ac.label}</span><span style={{fontFamily:'Manrope, sans-serif',fontSize:'0.75rem',fontWeight:600,color:ac.color,background:`${ac.color}15`,padding:'2px 8px',borderRadius:4}}>{ac.section}</span></div><button onClick={()=>sa(null)} aria-label="Close" style={{background:'none',border:'1px solid var(--slate-200)',borderRadius:8,padding:'8px 16px',cursor:'pointer',fontFamily:'Manrope, sans-serif',fontSize:'0.875rem',fontWeight:600,color:'var(--slate-600)',minHeight:44}}>Close <span aria-hidden="true">✕</span></button></div><div className="guide-two-col" style={{padding:20,gap:24,margin:0}}><div style={{flex:'1 1 55%',minWidth:0}}><p style={{fontFamily:'Manrope, sans-serif',fontSize:'0.9375rem',color:'var(--slate-700)',lineHeight:1.75,margin:0}}>{ac.plain}</p></div><aside style={{flex:'1 1 40%',minWidth:0}}><div style={{background:'#FFFBF7',borderLeft:'3px solid #C2410C',borderRadius:'0 10px 10px 0',padding:'16px 18px'}}><p style={{fontFamily:'Manrope, sans-serif',fontSize:'0.7rem',fontWeight:700,letterSpacing:'0.1em',textTransform:'uppercase',color:'var(--slate-500)',margin:'0 0 8px'}}>Official Standard — {pc(ac.citation)}</p><p style={{fontFamily:'Manrope, sans-serif',fontSize:'0.875rem',color:'var(--slate-600)',lineHeight:1.7,margin:0,fontStyle:'italic'}}>{pc(ac.legal)}</p></div></aside></div></div>)}
<style>{`@keyframes ktF{from{opacity:0;transform:translateY(-8px)}to{opacity:1;transform:translateY(0)}}`}</style></div>)}