/**
 * AdminLayout — shell for all /admin/* routes.
 *
 * Sidebar nav on the left, content on the right. Header shows the
 * signed-in admin's email and a sign-out button. Matches the public
 * site's typographic language but with a slightly denser, more
 * functional feel (admin is a tool, not a marketing surface).
 *
 * Ref: docs/ARCHITECTURE.md §11
 */

import { useEffect, useState } from 'react';
import { useUser, useClerk } from '@clerk/clerk-react';
import { Link, NavLink, Outlet, useLocation } from 'react-router-dom';
import { PortalAnnouncerProvider } from '../portal/announcer.js';
import LiveAnnouncer from '../components/a11y/LiveAnnouncer.js';
import { ReadingLevelProvider } from '../components/standards/ReadingLevelContext.js';
import { AccessibilityPanel } from '../components/AccessibilityPanel.js';

/**
 * The primary site links, mirrored from PublicLayout. Declared here so
 * the admin chrome carries the same nav; adminChromeParity asserts the
 * two lists stay identical.
 */
const SITE_NAV = [
  { to: '/standards-guide', label: 'ADA Standards Guide' },
  { to: '/attorneys', label: 'Find an Attorney' },
  { to: '/lawsuits', label: 'Lawsuits' },
];

/**
 * Nav structure, adopted from Base44's AdminLayout (@ 6b1e9ac) so Gina's
 * muscle memory survives the cutover: Overview / Ada / Directory /
 * Business / System, in that order, with B44's labels.
 *
 * Four deliberate differences from B44's list:
 *
 *   - CASES is here and has no B44 counterpart — the placement queue was
 *     built on this side and is live. It sits under "Ada" because that is
 *     what it is: work generated by an Ada intake. PHOTO REVIEW is also
 *     Vercel-only but sits under SPOT (see below).
 *   - SUBSCRIBERS is dropped (decision o4). It is a marketplace-era stub
 *     over a billing model that does not exist.
 *   - DASHBOARD and FEEDBACK landed in M6 Phase 3. Dashboard is the
 *     Overview group; Feedback sits under BUSINESS — it is operational
 *     signal about the product, read alongside Analytics, not a
 *     configuration surface.
 *   - SPOT has its own group. Ada and Spot are different products — a
 *     legal-intake assistant and a paid photo-screening tool — and were
 *     sharing the Ada group. Spot, Spot Review, and Photo Review sit in a
 *     Spot section of their own. Photo Review moved here because the
 *     analyzer it reviews is now driven mostly by Spot (paid screenings
 *     and retained free-read training photos). This is a divergence FROM
 *     B44, so a later "sync from B44" must not re-merge it
 *     (adminNavParity.test.ts pins the split).
 *
 * LISTINGS is B44's "Class Actions" + "Mass Actions" pair behind one
 * page; Phase 3 decides whether to split it or keep the union.
 */
interface NavItem {
  to: string;
  label: string;
}

interface NavSection {
  label: string;
  items: NavItem[];
}

const NAV_SECTIONS: NavSection[] = [
  {
    label: 'Overview',
    items: [{ to: '/admin/dashboard', label: 'Dashboard' }],
  },
  {
    label: 'Ada',
    items: [
      { to: '/admin/sessions', label: 'Sessions' },
      { to: '/admin/intakes', label: 'Intakes / Referrals' },
      { to: '/admin/cases', label: 'Cases' },
    ],
  },
  {
    label: 'Spot',
    items: [
      { to: '/admin/spot', label: 'Spot' },
      { to: '/admin/spot-review', label: 'Spot Review' },
      { to: '/admin/photo-review', label: 'Photo Review' },
      { to: '/admin/spot/annotation-preview', label: 'Annotation Preview' },
    ],
  },
  {
    label: 'Directory',
    items: [
      { to: '/admin/firms', label: 'Firms' },
      { to: '/admin/attorneys', label: 'Attorneys' },
      { to: '/admin/litigation', label: 'Class & Mass Actions' },
      { to: '/admin/listings', label: 'Firm Listings' },
    ],
  },
  {
    label: 'Business',
    items: [
      { to: '/admin/analytics', label: 'Analytics' },
      { to: '/admin/feedback', label: 'Feedback' },
    ],
  },
  {
    label: 'System',
    items: [
      { to: '/admin/email', label: 'Email' },
      { to: '/admin/settings', label: 'Settings' },
    ],
  },
];

export default function AdminLayout() {
  const { user } = useUser();
  const { signOut } = useClerk();
  const location = useLocation();

  const email = user?.primaryEmailAddress?.emailAddress ?? 'admin';

  /**
   * How many messages are waiting, for the badge on Feedback.
   *
   * Re-read on every navigation rather than once on mount, so marking
   * something reviewed drops the count without a page refresh. A failed
   * read shows no badge — an admin surface should not grow an error
   * banner because a decoration could not load.
   */
  const [newFeedback, setNewFeedback] = useState(0);
  useEffect(() => {
    let cancelled = false;
    void (async () => {
      try {
        const resp = await fetch('/api/admin/feedback?status=new&limit=1', {
          credentials: 'include',
        });
        if (!resp.ok) return;
        const body = (await resp.json()) as { counts?: { new?: number } };
        if (!cancelled) setNewFeedback(body.counts?.new ?? 0);
      } catch {
        /* no badge is the right failure here */
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [location.pathname]);

  return (
    <LiveAnnouncer>
    <ReadingLevelProvider>
    <PortalAnnouncerProvider>
    <div className="admin-shell min-h-screen flex flex-col">
      {/* Skip link */}
      <a
        href="#admin-main"
        className="sr-only focus:not-sr-only focus:fixed focus:top-2 focus:left-2 focus:z-50 focus:px-4 focus:py-2 focus:bg-ink-900 focus:text-white focus:rounded"
      >
        Skip to main content
      </a>

      {/* Site chrome.
       *
       * Base44's admin renders inside the site layout, so Gina has the
       * nav and — the part that matters — the display-settings control
       * on every admin page. Ours had neither: the one surface she uses
       * daily was the one place she could not reach her own
       * accessibility settings, on a project whose floor is AAA.
       *
       * The bar is declared here rather than by wrapping /admin in
       * PublicLayout, which would nest a second <main>, a second skip
       * link and a duplicate #main-content id inside this one. The link
       * set is asserted against PublicLayout's by adminChromeParity so
       * the two cannot drift apart silently.
       *
       * AccessibilityPanel needs LiveAnnouncer and ReadingLevelProvider
       * above it: without them the panel still renders, but the
       * reading-level control becomes a silent no-op and announcements
       * are dropped — a control that looks live and does nothing is
       * worse than one that is absent.
       */}
      <header className="admin-seam bg-brand-navy text-white relative z-40 flex-none">
        <div
          className="w-full flex items-center justify-between"
          style={{ height: 72, padding: '0 clamp(16px, 4vw, 40px)' }}
        >
          <Link
            to="/"
            className="flex items-center gap-3 font-display font-bold text-white no-underline"
            style={{ fontSize: '1.5rem' }}
            aria-label="ADA Legal Link home"
          >
            <img
              src="/logo-transparent.png"
              alt=""
              width="44"
              height="44"
              className="w-11 h-11 object-contain flex-shrink-0"
            />
            <span className="whitespace-nowrap">
              ADA Legal <span style={{ color: '#FDBA74' }}>Link</span>
            </span>
          </Link>

          <div className="flex items-center gap-1 sm:gap-2">
            <nav aria-label="Primary" className="hidden md:flex items-center gap-1 font-chrome">
              {SITE_NAV.map((item) => (
                <Link
                  key={item.to}
                  to={item.to}
                  className="transition-colors inline-flex items-center text-white hover:text-brand-gold"
                  style={{ fontSize: '0.9375rem', fontWeight: 500, minHeight: 44, padding: '6px 12px' }}
                >
                  {item.label}
                </Link>
              ))}
            </nav>
            <AccessibilityPanel onDark />
          </div>
        </div>
      </header>

      <div className="flex-1 min-h-0 flex flex-col md:flex-row">
      {/* Sidebar — B44 puts the brand here, not in the header bar. */}
      <aside className="admin-sidebar md:w-60 md:flex-none px-4 py-6">
        {/* No wordmark here. The site bar directly above already carries
            it, and two identical lockups ten pixels apart — linking to
            different destinations — is a trap, not branding. */}
        <div className="mb-5 px-2.5">
          <div className="admin-kicker text-[0.8125rem] font-medium uppercase tracking-[0.1em]">
            Admin
          </div>
        </div>

        <nav aria-label="Admin sections" className="flex md:flex-col gap-1 md:gap-5 overflow-x-auto">
          {NAV_SECTIONS.map((section) => (
            <div key={section.label} className="flex md:flex-col gap-1 md:gap-0.5">
              {/* Group headings are real headings, not styled spans, so a
                  screen-reader user can navigate the sidebar by heading
                  rather than walking every link. */}
              {/* 13px, not B44's 11px. Uppercase at 11px with .15em
                  tracking is the least legible text on the screen, and
                  these are the labels that make the rail scannable. */}
              <h2 className="admin-kicker hidden md:block px-2.5 pb-2 text-[0.8125rem] font-medium uppercase tracking-[0.1em]">
                {section.label}
              </h2>
              {section.items.map((item) => (
                <NavLink
                  key={item.to}
                  to={item.to}
                  className={({ isActive }) =>
                    // 44px minimum target: Gina navigates by knuckle.
                    // pl-6 against the label's pl-2.5: the indent is what
                    // makes an item read as belonging to its section.
                    'admin-navlink flex items-center min-h-[44px] pl-6 pr-2.5 py-2 rounded-md text-sm whitespace-nowrap no-underline transition-colors ' +
                    (isActive ? 'is-active font-semibold' : '')
                  }
                >
                  {item.label}
                  {item.to === '/admin/feedback' && newFeedback > 0 && (
                    <span
                      className="ml-2 inline-flex min-w-[1.5rem] justify-center rounded-full bg-accent-500 px-2 py-0.5 text-xs font-bold text-white"
                      // The number is read out as part of the link, so a
                      // screen-reader user hears "Feedback, 3 waiting"
                      // rather than "Feedback, 3".
                      aria-label={`${newFeedback} waiting`}
                    >
                      {newFeedback}
                    </span>
                  )}
                </NavLink>
              ))}
            </div>
          ))}
        </nav>
      </aside>

      {/* Main column */}
      <div className="flex-1 min-w-0 flex flex-col">
        <header className="admin-topbar flex items-center justify-end gap-4 px-8 py-4">
          <span className="admin-topbar-email hidden sm:inline text-xs">{email}</span>
          <button
            type="button"
            onClick={() => signOut({ redirectUrl: '/' })}
            className="admin-topbar-signout text-sm underline underline-offset-2 min-h-[44px]"
          >
            Sign out
          </button>
        </header>

        <main
          id="admin-main"
          className="flex-1 min-w-0 w-full max-w-[1280px] mx-auto px-5 sm:px-8 py-8"
          key={location.pathname}
        >
          <Outlet />
        </main>
      </div>
      </div>
    </div>
    </PortalAnnouncerProvider>
    </ReadingLevelProvider>
    </LiveAnnouncer>
  );
}
