/**
 * AdminLayout — shell for all /admin/* routes.
 *
 * Sidebar nav on the left, content on the right. Header shows the
 * signed-in admin's email and a sign-out button. Matches the public
 * site's typographic language but with a slightly denser, more
 * functional feel (admin is a tool, not a marketing surface).
 *
 * Ref: docs/ARCHITECTURE.md §11
 */

import { useUser, useClerk } from '@clerk/clerk-react';
import { Link, NavLink, Outlet, useLocation } from 'react-router-dom';
import { PortalAnnouncerProvider } from '../portal/announcer.js';

/**
 * Nav structure, adopted from Base44's AdminLayout (@ 6b1e9ac) so Gina's
 * muscle memory survives the cutover: Overview / Ada / Directory /
 * Business / System, in that order, with B44's labels.
 *
 * Three deliberate differences from B44's list:
 *
 *   - CASES and PHOTO REVIEW are here and have no B44 counterpart. The
 *     placement queue and the photo-analysis review flow were built on
 *     this side and are live. They sit under "Ada" because that is what
 *     they are: work generated by an Ada intake.
 *   - SUBSCRIBERS is dropped (decision o4). It is a marketplace-era stub
 *     over a billing model that does not exist.
 *   - DASHBOARD and FEEDBACK landed in M6 Phase 3 and are now the
 *     Overview group and an Ada-group entry respectively. Feedback sits
 *     under Ada rather than System because it is what people say after
 *     using her, not a configuration surface.
 *
 * LISTINGS is B44's "Class Actions" + "Mass Actions" pair behind one
 * page; Phase 3 decides whether to split it or keep the union.
 */
interface NavItem {
  to: string;
  label: string;
}

interface NavSection {
  label: string;
  items: NavItem[];
}

const NAV_SECTIONS: NavSection[] = [
  {
    label: 'Overview',
    items: [{ to: '/admin/dashboard', label: 'Dashboard' }],
  },
  {
    label: 'Ada',
    items: [
      { to: '/admin/sessions', label: 'Sessions' },
      { to: '/admin/intakes', label: 'Intakes / Referrals' },
      { to: '/admin/cases', label: 'Cases' },
      { to: '/admin/photo-review', label: 'Photo Review' },
      { to: '/admin/feedback', label: 'Feedback' },
    ],
  },
  {
    label: 'Directory',
    items: [
      { to: '/admin/firms', label: 'Firms' },
      { to: '/admin/attorneys', label: 'Attorneys' },
      { to: '/admin/listings', label: 'Class & Mass Actions' },
    ],
  },
  {
    label: 'Business',
    items: [{ to: '/admin/analytics', label: 'Analytics' }],
  },
  {
    label: 'System',
    items: [{ to: '/admin/settings', label: 'Settings' }],
  },
];

export default function AdminLayout() {
  const { user } = useUser();
  const { signOut } = useClerk();
  const location = useLocation();

  const email = user?.primaryEmailAddress?.emailAddress ?? 'admin';

  return (
    <PortalAnnouncerProvider>
    <div className="admin-shell min-h-screen bg-surface-50 text-ink-900 flex flex-col">
      {/* Skip link */}
      <a
        href="#admin-main"
        className="sr-only focus:not-sr-only focus:fixed focus:top-2 focus:left-2 focus:z-50 focus:px-4 focus:py-2 focus:bg-ink-900 focus:text-surface-50 focus:rounded"
      >
        Skip to main content
      </a>

      {/* Top bar */}
      <header className="border-b border-surface-200 bg-white">
        <div className="max-w-6xl mx-auto px-5 sm:px-8 py-3 flex items-center justify-between gap-4">
          <Link
            to="/admin/sessions"
            className="font-display text-lg text-ink-900 hover:text-accent-600 transition-colors"
            aria-label="ADA Legal Link admin home"
          >
            ADA <span className="text-accent-500">Legal</span> Link
            <span className="text-ink-500 font-mono text-xs ml-2 tracking-widest uppercase">
              Admin
            </span>
          </Link>
          <div className="flex items-center gap-4 text-sm">
            <span className="text-ink-500 hidden sm:inline font-mono text-xs">{email}</span>
            <button
              type="button"
              onClick={() => signOut({ redirectUrl: '/' })}
              className="text-ink-700 hover:text-accent-600 underline underline-offset-2"
            >
              Sign out
            </button>
          </div>
        </div>
      </header>

      {/* Body: sidebar + main */}
      <div className="flex-1 max-w-6xl w-full mx-auto flex flex-col md:flex-row gap-6 px-5 sm:px-8 py-6">
        <aside className="md:w-48 md:flex-none">
          <nav aria-label="Admin sections" className="flex md:flex-col gap-1 md:gap-4 overflow-x-auto">
            {NAV_SECTIONS.map((section) => (
              <div key={section.label} className="flex md:flex-col gap-1 md:gap-0.5">
                {/* Group headings are real headings, not styled spans, so a
                    screen-reader user can navigate the sidebar by heading
                    rather than walking every link. */}
                <h2 className="hidden md:block px-3 pb-1 font-mono text-[0.65rem] uppercase tracking-[0.14em] text-ink-500">
                  {section.label}
                </h2>
                {section.items.map((item) => (
                  <NavLink
                    key={item.to}
                    to={item.to}
                    className={({ isActive }) =>
                      // 44px minimum target: Gina navigates by knuckle.
                      'flex items-center min-h-[44px] px-3 py-2 rounded-md text-sm whitespace-nowrap transition-colors ' +
                      (isActive
                        ? 'bg-accent-600 text-white font-medium'
                        : 'text-ink-700 hover:bg-surface-100 hover:text-accent-600')
                    }
                  >
                    {item.label}
                  </NavLink>
                ))}
              </div>
            ))}
          </nav>
        </aside>

        <main id="admin-main" className="flex-1 min-w-0" key={location.pathname}>
          <Outlet />
        </main>
      </div>
    </div>
    </PortalAnnouncerProvider>
  );
}
