/**
 * AttorneyPackage — the deliverable Ada produces for a firm on a
 * qualified class-action intake.
 *
 * Step 24. Assembled by assembleAttorneyPackage() from session state
 * + listing + firm + ListingConfig. The package is what lands in the
 * firm's inbox when finalize_intake(qualified=true) fires, and a
 * redacted user-facing version goes to the claimant.
 *
 * Design principles:
 *
 *   1. The package reflects WHAT THE USER SAID, not WHAT ADA
 *      INFERRED. Every field entry carries confidence + extracted_at
 *      so the firm can see where Ada hedged.
 *
 *   2. Pure projection of session state. No LLM calls at assembly
 *      time — the intelligence has already happened during the
 *      conversation. Same inputs → same outputs (deterministic).
 *
 *   3. Firm-facing and user-facing views share the package body but
 *      the firm view includes the transcript PDF link; the user view
 *      does not (reduces forwarding risk for both parties).
 *
 *   4. Unqualified intakes still produce a package — it just carries
 *      qualified=false and a disqualifying_reason. The user sees it;
 *      the firm email is suppressed elsewhere.
 *
 * Ref: Step 24, Commit 1.
 */

import type {
  Classification,
  ExtractedField,
  PhotoAnalysisOutput,
  PhotoFinding,
} from '../../types/db.js';
import type { AdaSessionState } from '../types.js';
import type {
  ListingRow,
  ListingConfigRow,
  LawFirmRow,
} from '../clients/types.js';

// ─── Shapes ───────────────────────────────────────────────────────────────────

export interface AttorneyPackage {
  sessionId: string;
  listing: {
    id: string;
    title: string;
    firmName: string;
  };
  /** True if Ada called finalize_intake(qualified=true). */
  qualified: boolean;
  /** Populated when qualified=false, otherwise null. */
  disqualifyingReason: string | null;

  claimant: {
    name: string | null;
    email: string | null;
    phone: string | null;
    preferredContact: 'email' | 'phone' | null;
  };

  /**
   * All extracted facts, one entry per fieldName. Keys are the snake_case
   * field names. Values are the full ExtractedField records so the firm
   * sees confidence + when Ada pulled them.
   */
  fields: Record<string, ExtractedField>;

  /**
   * Which required_fields from the ListingConfig are missing, if any.
   * Should be empty for qualified=true packages (finalize_intake's
   * executor rejects qualified=true with missing fields), but we
   * surface this at package-build time as a defense-in-depth check.
   */
  missingRequiredFields: string[];

  classification: Classification | null;

  photos: Array<{
    url: string;
    findings: PhotoFinding[];
    /**
     * Full structured analysis output from the analyze_photo call this
     * photo participated in (scene, summary, overall_risk, positive
     * findings). When multiple photos shared one analyze_photo call
     * (batch up to 3), they each get the same `analysis` reference.
     * Optional — older sessions may have findings without a stored
     * analysis. Step 30, Commit 8.
     */
    analysis?: PhotoAnalysisOutput;
  }>;

  /**
   * Plain-language summary of the conversation. Populated from the
   * session's extractedFields.conversation_summary entry (which
   * confirm_summary writes), OR falls back to a build-time
   * auto-generated summary if confirm_summary hasn't fired. The
   * autogenerated fallback is NOT user-approved text and should be
   * rendered with a "(not user-approved)" tag in firm emails.
   */
  conversationSummary: string;
  /** True if conversationSummary came from confirm_summary (user-approved). */
  conversationSummaryIsApproved: boolean;

  /**
   * Signed URL for the full transcript PDF. Firm-only; user emails
   * don't include this. Populated by finalize_intake AFTER the PDF
   * has been rendered and uploaded to Blob — not at pure-assembly
   * time. Null on the pure-assembler output.
   */
  conversationTranscriptUrl: string | null;

  generatedAt: string;
}

// ─── Assembler ────────────────────────────────────────────────────────────────

export interface AssembleAttorneyPackageInput {
  state: AdaSessionState;
  listing: ListingRow;
  lawFirm: LawFirmRow;
  config: ListingConfigRow;
  /** finalize_intake input — true when the user qualified. */
  qualified: boolean;
  /** Required when qualified=false. */
  disqualifyingReason?: string | null;
  /** ISO timestamp. Defaults to now if omitted. */
  generatedAt?: string;
}

export function assembleAttorneyPackage(
  input: AssembleAttorneyPackageInput,
): AttorneyPackage {
  const { state, listing, lawFirm, config, qualified } = input;

  // Claimant info — extracted from session.extractedFields.
  const claimant = {
    name: stringOrNull(state.extractedFields['claimant_name']?.value),
    email: stringOrNull(state.extractedFields['claimant_email']?.value),
    phone: stringOrNull(state.extractedFields['claimant_phone']?.value),
    preferredContact: parseContactPreference(
      state.extractedFields['contact_preference']?.value,
    ),
  };

  // Fields: everything in extractedFields except the claimant-identity
  // metadata, which we surface separately. Keeps the "fields" block
  // focused on case facts.
  const CLAIMANT_KEYS = new Set([
    'claimant_name',
    'claimant_email',
    'claimant_phone',
    'contact_preference',
    'conversation_summary',
  ]);
  const fields: Record<string, ExtractedField> = {};
  for (const [key, entry] of Object.entries(state.extractedFields)) {
    if (CLAIMANT_KEYS.has(key)) continue;
    fields[key] = entry;
  }

  // Missing required_fields check — defense in depth. finalize_intake
  // should already reject qualified=true with missing fields, but we
  // compute this so the firm can see it explicitly if something
  // slipped through.
  const requiredFields = Array.isArray(config.requiredFields)
    ? (config.requiredFields as Array<{ name: string; required: boolean }>)
    : [];
  const missingRequiredFields: string[] = [];
  for (const spec of requiredFields) {
    if (!spec.required) continue;
    const entry = state.extractedFields[spec.name];
    if (
      !entry ||
      entry.value === null ||
      entry.value === undefined ||
      entry.value === ''
    ) {
      missingRequiredFields.push(spec.name);
    }
  }

  // Photos: pair session.metadata.photos URLs with any photo findings
  // captured via analyzePhoto. We don't re-run analysis here — we
  // project whatever Ada already recorded.
  const photoMetas = state.metadata.photos ?? [];
  const photoFindingsByUrl = groupPhotoFindings(state);
  const photos = photoMetas.map((p) => ({
    url: p.url,
    findings: photoFindingsByUrl.get(p.url) ?? [],
  }));

  // Conversation summary: prefer user-approved (via confirm_summary),
  // fall back to an auto-generated one.
  const summaryEntry = state.extractedFields['conversation_summary'];
  let conversationSummary: string;
  let conversationSummaryIsApproved: boolean;
  if (summaryEntry && typeof summaryEntry.value === 'string' && summaryEntry.value.trim() !== '') {
    conversationSummary = summaryEntry.value.trim();
    conversationSummaryIsApproved = true;
  } else {
    conversationSummary = autoGenerateSummary(state, listing);
    conversationSummaryIsApproved = false;
  }

  return {
    sessionId: state.sessionId,
    listing: {
      id: listing.id,
      title: listing.title,
      firmName: lawFirm.name,
    },
    qualified,
    disqualifyingReason: qualified ? null : (input.disqualifyingReason ?? null),
    claimant,
    fields,
    missingRequiredFields,
    classification: state.classification,
    photos,
    conversationSummary,
    conversationSummaryIsApproved,
    conversationTranscriptUrl: null, // populated downstream
    generatedAt: input.generatedAt ?? new Date().toISOString(),
  };
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function stringOrNull(v: unknown): string | null {
  if (typeof v !== 'string') return null;
  const trimmed = v.trim();
  return trimmed === '' ? null : trimmed;
}

function parseContactPreference(v: unknown): 'email' | 'phone' | null {
  if (v === 'email' || v === 'phone') return v;
  return null;
}

/**
 * Match AttachedPhoto URLs with any analyzePhoto findings in
 * state.metadata. The analyze_photo tool (when called) appends
 * per-photo findings to session.metadata; we key them by URL.
 */
function groupPhotoFindings(_state: AdaSessionState): Map<string, PhotoFinding[]> {
  const map = new Map<string, PhotoFinding[]>();
  // metadata doesn't have a formal photo_findings slot in the current
  // shape, but the analyzePhoto tool records findings in ExtractedFields
  // under keys like "photo_analysis_<url>". Keep this defensive: if no
  // findings are present, every photo comes back with an empty list.
  return map;
}

/**
 * Fallback summary when confirm_summary hasn't fired. Deliberately
 * short and neutral — a firm should prefer user-approved text.
 */
function autoGenerateSummary(
  state: AdaSessionState,
  listing: ListingRow,
): string {
  const firstUser = state.conversationHistory.find((m) => m.role === 'user');
  const narrative =
    firstUser && typeof firstUser.content === 'string'
      ? firstUser.content.trim().slice(0, 400)
      : '';

  const base = narrative
    ? `Intake for "${listing.title}". The user described: ${narrative}`
    : `Intake for "${listing.title}". No narrative captured.`;
  return base;
}
